version: '3.1'
services:

  php:
    build:
      context: ./php
    volumes:
      - ../:/app
    working_dir: /app
    ports:
      - "8000:8000"

  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: bp_challenge
      MYSQL_USER: bpuser
      MYSQL_PASSWORD: bppass